version: 2
jobs:
  build:
    docker:
      - image: jcg582/circleci-docker-gcloud-ubuntu
    steps:
      - checkout
      - setup_remote_docker
      - run: make build
      - run: make setup_gcloud_stg
      - run: make push_image
      - run: make setup_gcloud_prod
      - run: make push_image
  deploy_to_staging:
    docker:
      - image: jcg582/circleci-docker-gcloud-ubuntu
    steps:
      - checkout
      - setup_remote_docker
      - run: make setup_gcloud_stg
      - run: make deploy_stg
  deploy_to_prod:
    docker:
      - image: jcg582/circleci-docker-gcloud-ubuntu
    steps:
      - checkout
      - setup_remote_docker
      - run: make setup_gcloud_prod
      - run: make deploy_prod

workflows:
  version: 2
  build_test_and_deploy:
    jobs:
      - build
      - trigger_deploy_to_staging:
          type: approval
          requires:
            - build
      - deploy_to_staging:
          requires:
            - trigger_deploy_to_staging
      - trigger_deploy_to_prod:
          type: approval
          requires:
            - deploy_to_staging
      - deploy_to_prod:
          requires:
            - trigger_deploy_to_prod
