version: 2
jobs:
  build:
    docker:
      - image: jcg582/circleci-docker-gcloud-ubuntu
    steps:
      - checkout
      - setup_remote_docker
      - run: make build
      - run: make test
      - run: make setup_gcloud
      - run: make push_image
  deploy_to_staging:
    docker:
      - image: jcg582/circleci-docker-gcloud-ubuntu
    steps:
      - checkout
      - setup_remote_docker
      - run: make setup_gcloud
      - run: make deploy_to_gke

workflows:
  version: 2
  build_test_and_deploy:
    jobs:
      - build
      - trigger_deploy_to_staging:
          type: approval
          requires:
            - build
      - deploy_to_staging:
          requires:
            - trigger_deploy_to_staging
